from PIL import ImageColor
print('red RGBA')
print(ImageColor.getcolor('red','RGBA'))
print('RED RGBA')
print(ImageColor.getcolor('RED','RGBA'))
print('Black RGBA')
print(ImageColor.getcolor('Black','RGBA'))
print('chocolate RGBA')
print(ImageColor.getcolor('chocolate','RGBA'))
print('CornFlowerBlue RGBA')
print(ImageColor.getcolor('CornFlowerBlue','RGBA'))
